name: Build and deploy gender API

on:
  push:
    branches:
      - 'main'

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Auth GCP gcloud
        uses: 'google-github-actions/auth@v1'
        with:
            credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build docker
        working-directory: api
        run: docker build -t gender-api .

      - name: Tag the image
        run: docker tag gender-api europe-docker.pkg.dev/ensai-2025/test-christophe/gender-api

      - name: Authenticate to GCP registry
        run: gcloud auth configure-docker europe-docker.pkg.dev

      - name: Create the repo
        run: gcloud artifacts repositories create test-christophe --repository-format docker --location europe

      - name: Push to GCP registry
        run: docker push europe-docker.pkg.dev/ensai-2025/test-christophe/gender-api

    deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
      - name: Auth GCP gcloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'christophe-gender-api'
          image: 'europe-docker.pkg.dev/ensai-2025/test-christophe/gender-api'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
